Error: Reference to undeclared resource
  on .terraform/modules/bastion_linux/outputs.tf line 3, in output "bastion_private_ip":
   3:   value       = aws_instance.bastion_linux.private_ip

A managed resource "aws_instance" "bastion_linux" has not been declared in
module.bastion_linux.
Error: Process completed with exit code 1.