Error: Incorrect attribute value type
  on .terraform/modules/bastion_linux/main.tf line 451, in resource "aws_autoscaling_group" "bastion_linux_daily":
 451:   tags = merge(
 452:     var.tags_common,
 453:     {
 454:       Name = "bastion_linux"
 455:     }
 456:   )
    ├────────────────
    │ var.tags_common is map of string with 7 elements

Inappropriate value for attribute "tags": set of map of string required.
module.windows-ecs.aws_autoscaling_group.cluster-scaling-group: Refreshing state... [id=<REDACTED>]