Warning: Quoted references are deprecated
  on .terraform/modules/bastion_linux/outputs.tf line 2, in data "aws_instances" "ecs_instances_meta":
   2:   depends_on = [ "aws_autoscaling_group.bastion_linux_daily" ]

In this context, references are expected literally rather than in quotes.
Terraform 0.11 and earlier required quotes, but quoted references are now
deprecated and will be removed in a future version of Terraform. Remove the
quotes surrounding this reference to silence this warning.
Error: Process completed with exit code 1.