Fix private IP reference and autoscaling group tags (#19)
* Error: Reference to undeclared resource

  on .terraform/modules/bastion_linux/outputs.tf line 3, in output "bastion_private_ip":
   3:   value       = aws_instance.bastion_linux.private_ip

A managed resource "aws_instance" "bastion_linux" has not been declared in
module.bastion_linux.
Error: Process completed with exit code 1.

* Error: Invalid template interpolation value

  on db_manager.tf line 137, in resource "aws_security_group" "db_mgmt_server_security_group":
 137:     cidr_blocks = ["${module.bastion_linux.bastion_private_ip}/32"]
    ├────────────────
    │ module.bastion_linux.bastion_private_ip is list of string with 1 element

* Error: Incorrect attribute value type

  on .terraform/modules/bastion_linux/main.tf line 451, in resource "aws_autoscaling_group" "bastion_linux_daily":
 451:   tags = merge(
 452:     var.tags_common,
 453:     {
 454:       Name = "bastion_linux"
 455:     }
 456:   )
    ├────────────────
    │ var.tags_common is map of string with 7 elements

Inappropriate value for attribute "tags": set of map of string required.
module.windows-ecs.aws_autoscaling_group.cluster-scaling-group: Refreshing state... [id=<REDACTED>]